### ISSUE TITLE
Failing on make step

### ISSUE THREAD

**Issue by 256k** [flpDiskJ/Octopus-tracker#2]
hello, i just cloned the repo and trying to build on macOS M1 pro Sonoma 14.7 and i get an error on the make step
```
[  8%] Building CXX object CMakeFiles/octopus.dir/src/main.cpp.o
In file included from /Users/fhelmi/projects/Octopus-tracker/src/main.cpp:5:
In file included from /Users/fhelmi/projects/Octopus-tracker/src/headers/tracker.h:3:
/Users/fhelmi/projects/Octopus-tracker/src/headers/global.h:4:17: warning: using directive refers to implicitly-defined namespace 'std'
    4 | using namespace std;
      |                 ^
/Users/fhelmi/projects/Octopus-tracker/src/headers/global.h:7:10: fatal error: 'string' file not found
    7 | #include <string>
      |          ^~~~~~~~
1 warning and 1 error generated.
make[2]: *** [CMakeFiles/octopus.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/octopus.dir/all] Error 2
make: *** [all] Error 2
```

Not sure if it's something wrong on my computer or not. SDL and SDL_ttf installed correctly and the cmake step ran fine.

```
Apple clang version 16.0.0 (clang-1600.0.26.3)
Target: arm64-apple-darwin23.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by flpDiskJ** [comment]
Looks like declaring 
`using namespace std;`
before linking any standard libs is the reason for the first warning.
I have now fixed this so try pulling and recompiling.

As for the second I believe it is a compiler issue on your end. Try installing g++
